sudo: enable
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script: bundle exec rspec

stages:
  - test
  - deploy

jobs:
  include:
    - stage: deploy
      cache: false
      if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      deploy:
        script: skip
        provider: rubygems
        api_key:
          secure: sXU46GiEXwTfPx8AwTWuBJg6bUZWvjDgJR/bEUGMXoW4R5Q4XlLAOflwAtGpXY6YXI/RNBYD1GM2AyVdTDa/fnO1sViF1pJSXsD+XvnxB0LNbTuLPRfzJ2M15vYcqEyG2AhRPb+epe+IMQ60wXcOrwZjHzHoH5tutBo8dY+dqxkpCQiZke1MoH+ocfL9f9gtdGvaexMvDNRgwaYw5pjaWr0RKez+bHvEhVPdugyHcvHjjXJGTmYKyVap0yewojxDWpD2Rp/2HDg+Xsi3KqJ9gWrpQtVx4mSlSx80eI9N5jgiyxkRvZOVmJ1B532QFLCo0BLtrMfFD/zErUQ+MsRmtgNR66HnRNtBoGDRhn82bvdsr4bx0f+poUwZxDlv/oqqqRvPGNfDzsy3Qt8G3bAyZO+cKsGxFclnGCE94JdGtopnXEJ+YU2gfnUBUk8LFHj6YNwfVCrXU6dLDx0J8mWIkdFkTqOiLZMRKS0LYRrcCmOed0Jlkt1JprMUUDesR+79dxC2ESbbtd4Dyur2PIT6cTm959lxS5HBaIumF/W4qxzWU0DvXvOqDjiujlwMqHJq7FPPG96tZnmwrFXkGSOhv6ebsAYIp4t6CU28zOFHKzqy5xHsApEX7GHV2ZOOgHExWngKX03aPcsMv99ncn6kXGQHevYnofZAguoLXAddoIk=
        gem: fluent-plugin-statsd-output
        on:
          tags: true
          repo: imnotjames/fluent-plugin-statsd
