sudo: enable
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
script: bundle exec rspec
stages:
  - test
  - deploy
jobs:
  include:
    - stage: deploy
      cache: false
      if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      deploy:
        script: skip
        provider: rubygems
        api_key:
          secure: hIk7N6BjLuQDNJWXEc4fZPPqcygxmvQ8IDMitY3rVaXK8+1OJEutHT/ehOhBWMjEvS70OTnCYwo6cpoQkvCmW/V6cchnt5PIBdEQ4vILEh8OP2nB72AhwxnbUOgJ2Uk+EPt1XGJPqUQ0/ZqaP6uIIYClh9s9yAxQWrkJfQrecRJF2WzwWoNVXXCl0+UuH/pcKVo5jaL56zxQTOePdEcBrm/EB3YqAmdW7wHsXnm0CaWWO5VJ/6PJHlyUW4jd5EJBYesPoAEzZwjPhUqNCcg9KqHJSce41WD6eaVHdnqyUwdZCO6OOpXTSArw1XykXX/Z4EXd2QOP/g84XG6vk10hoy9+UomHxFMtGk1AP6vMOLxn9q7zF43S/as6AQdHAnegnWYZxQpW41DSXrqgOWxIFYznR/ZmD8zJR20hgXdMgYjGZq10Wy/i8Y2SUDfojuw5OGej9OehXYQ8ZBNkdSN4U5AiGYrCBOy2WGbiDehIR/EVN5yiUS6WapcRWZ2Ia9vUDgUXHOW2OdUw5N1FR1uJ+dLr5oihD6g7nweFa6qsJb+88ecz+nby9dgL+WTVlzOzBshE8q5UcdS5959wnShHUtEZP5yQDmWn4u/haL+osEO0PRu8KLick6lYzSNO0HEEELEV76mSHI+UKVZxG8T7E+WUEoskxtRn3aomQOKvQkA=
        gem: fluent-plugin-statsd-output
        on:
          tags: true
          repo: imnotjames/fluent-plugin-statsd
